version: '3.8'

services:
  nextjs-app-dev:
    build:
      context: ./my-nextjs-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-nextjs-app:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev

  nextjs-app-prod:
    build:
      context: ./my-nextjs-app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
