name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
      working-directory: ./my-nextjs-app
    - name: Build
      run: npm run build
      working-directory: ./my-nextjs-app
    - name: Lint
      run: npm run lint
      working-directory: ./my-nextjs-app
    # Add test step here when you have tests
    # - name: Test
    #   run: npm test
    #   working-directory: ./my-nextjs-app

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        if [ -z "$PRIVATE_KEY" ] || [ -z "$HOST" ] || [ -z "$USER" ]; then
          echo "Error: One or more required secrets are missing."
          exit 1
        fi
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          cd /home/cj4ck/env-test &&
          git pull origin main
        '
    - name: Cleanup
      if: always()
      run: rm -f private_key
